#!/usr/bin/env bash
set -euo pipefail

# ---------------------------------------------------------------------------
# Posts a Claude-QA analysis as a PR comment via the GitHub CLI.
#
# Usage: post-report.sh <PR_NUMBER> <ANALYSIS_JSON_PATH>
# ---------------------------------------------------------------------------

PR_NUMBER="${1:?Usage: post-report.sh <PR_NUMBER> <ANALYSIS_JSON_PATH>}"
ANALYSIS_FILE="${2:?Usage: post-report.sh <PR_NUMBER> <ANALYSIS_JSON_PATH>}"

if [[ ! -f "$ANALYSIS_FILE" ]]; then
  echo "ERROR: Analysis file not found: $ANALYSIS_FILE"
  exit 1
fi

if ! command -v jq &>/dev/null; then
  echo "WARNING: jq not found — posting raw JSON as comment."
  gh pr comment "$PR_NUMBER" --body "$(cat <<EOF
## Claude-QA Analysis

\`\`\`json
$(cat "$ANALYSIS_FILE")
\`\`\`
EOF
)"
  exit 0
fi

# ---------------------------------------------------------------------------
# Extract fields from analysis JSON
# ---------------------------------------------------------------------------
RISK=$(jq -r '.risk.level // "UNKNOWN"' "$ANALYSIS_FILE")
REASONING=$(jq -r '.risk.reasoning // "N/A"' "$ANALYSIS_FILE")
SUMMARY=$(jq -r '.summary // "No summary available."' "$ANALYSIS_FILE")
PR_TITLE=$(jq -r '.pr.title // "Unknown"' "$ANALYSIS_FILE")

RISK_EMOJI="white_check_mark"
case "$RISK" in
  LOW)      RISK_EMOJI="white_check_mark" ;;
  MEDIUM)   RISK_EMOJI="yellow_circle"    ;;
  HIGH)     RISK_EMOJI="orange_circle"    ;;
  CRITICAL) RISK_EMOJI="red_circle"       ;;
esac

# ---------------------------------------------------------------------------
# Build file change table
# ---------------------------------------------------------------------------
FILES_TABLE=$(jq -r '
  .files_changed // [] | map(
    "| `\(.path)` | \(.category) | \(.change_type) | \(.description) |"
  ) | join("\n")
' "$ANALYSIS_FILE")

# ---------------------------------------------------------------------------
# Build testing recommendations
# ---------------------------------------------------------------------------
TESTING_RECS=$(jq -r '
  def fmt(label; arr):
    if (arr | length) > 0
    then "**\(label):**\n" + (arr | map("- \(.)") | join("\n")) + "\n"
    else ""
    end;
  .recommended_testing as $t |
  [
    fmt("Unit Tests"; $t.unit // []),
    fmt("Integration Tests"; $t.integration // []),
    fmt("E2E / Browser Tests"; $t.e2e // []),
    fmt("Regression Tests"; $t.regression // []),
    fmt("Manual Review"; $t.manual_review // [])
  ] | map(select(. != "")) | join("\n")
' "$ANALYSIS_FILE")

# ---------------------------------------------------------------------------
# Build impact section
# ---------------------------------------------------------------------------
IMPACT_SECTION=$(jq -r '
  def bullet(arr): arr // [] | map("- \(.)") | join("\n");
  .impact as $i |
  "**Direct:**\n" + bullet($i.direct) + "\n\n" +
  "**Indirect:**\n" + bullet($i.indirect) + "\n\n" +
  "**Breaking Risks:**\n" + bullet($i.breaking_risks)
' "$ANALYSIS_FILE")

# ---------------------------------------------------------------------------
# Compose the comment
# ---------------------------------------------------------------------------
COMMENT_BODY=$(cat <<EOF
## :robot: Claude-QA Analysis

**PR:** $PR_TITLE
**Risk:** :$RISK_EMOJI: **$RISK**

### Summary

$SUMMARY

### Risk Assessment

$REASONING

**Increasing factors:**
$(jq -r '(.risk.increasing_factors // []) | map("- \(.)") | join("\n")' "$ANALYSIS_FILE")

**Decreasing factors:**
$(jq -r '(.risk.decreasing_factors // []) | map("- \(.)") | join("\n")' "$ANALYSIS_FILE")

### Files Changed

| File | Category | Change | Description |
|------|----------|--------|-------------|
$FILES_TABLE

### Impact

$IMPACT_SECTION

### Recommended Testing

$TESTING_RECS

---
*Generated by [Claude-QA](https://github.com/erayonder/Claude-QA) — AI-powered QA pipeline*
EOF
)

# ---------------------------------------------------------------------------
# Post (or update existing) comment
# ---------------------------------------------------------------------------
EXISTING_COMMENT_ID=$(gh api \
  "repos/{owner}/{repo}/issues/$PR_NUMBER/comments" \
  --jq '.[] | select(.body | startswith("## :robot: Claude-QA")) | .id' \
  2>/dev/null | head -1 || true)

if [[ -n "$EXISTING_COMMENT_ID" ]]; then
  echo "Updating existing Claude-QA comment ($EXISTING_COMMENT_ID)..."
  gh api \
    --method PATCH \
    "repos/{owner}/{repo}/issues/comments/$EXISTING_COMMENT_ID" \
    -f body="$COMMENT_BODY" \
    > /dev/null
else
  echo "Posting new Claude-QA comment..."
  gh pr comment "$PR_NUMBER" --body "$COMMENT_BODY"
fi

echo "Report posted to PR #$PR_NUMBER."
